repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: ["--autofix", "--indent=2", "--no-sort-keys"]
