name: carbonplan
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - adlfs
  - awscli
  - azure-storage-blob
  - bash-completion
  - bokeh
  - boto3
  - bottleneck
  - cartopy
  - cftime
  - cmip6_preprocessing
  - code-server >=3.2
  - fastparquet
  - fuzzywuzzy
  - gcsfs
  - gdal
  - geopandas
  - geoviews
  - gh-scoped-creds
  - git
  - git-crypt
  - graphviz
  - h5netcdf
  - h5py
  - htop
  - hvplot
  - hypothesis
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipytree
  - jupyter
  - jupyterhub-singleuser>=3.0,<4.0
  - jupyter-vscode-proxy
  - kubernetes
  - matplotlib
  - nb_conda_kernels
  - nc-time-axis
  - netcdf4
  - nodejs
  - numba
  - numcodecs
  - numpy
  - oauth2client
  - openpyxl
  - pandas
  - pangeo-dask>=2023.01
  - pangeo-notebook >= 2023.01
  - pip
  - pre_commit
  - prefect>=2.0
  - pydap
  - pygeos
  - pygraphviz
  - pyjanitor
  - pykdtree
  - pyproj
  - pyresample
  - pysal
  - pystac
  - pytest
  - python-graphviz
  - python-wget
  - rasterio
  - rechunker
  - regionmask
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - tzdata
  - vim
  - xarray
  - xclim
  - xesmf
  - xgboost
  - xlrd
  - xpublish
  - yarn
  - zarr

  - pip:
    - carbonplan-styles
    - git+https://github.com/fsspec/kerchunk.git
    - jupyterlab-s3-browser>=0.12
    - prefect-aws
