name: carbonplan-notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - code-server >=3.2
  - gh-scoped-creds
  - jupyterhub-singleuser>=3.0,<4.0
  - jupyter-vscode-proxy
  - numpy
  - pandas
  - pip
  - pre_commit
  - python-build
  - pytest
  - s3fs
  - xarray
  - zarr
