name: carbonplan
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - adlfs
  - awscli
  - azure-storage-blob
  - bash-completion
  - boto3
  - bottleneck
  - code-server >=3.2
  - gcsfs
  - gh-scoped-creds
  - git
  - git-crypt
  - jupyter
  - jupyterhub-singleuser>=3.0,<4.0
  - jupyter-vscode-proxy
  - matplotlib
  - netcdf4
  - nodejs
  - numcodecs
  - numpy
  - pandas
  - pip
  - pre_commit
  - pytest
  - python-graphviz
  - s3fs
  - vim
  - xarray
  - yarn
  - zarr

  - pip:
    - carbonplan[styles]
    - carbonplan[data]
    - git+https://github.com/fsspec/kerchunk.git
    - prefect-aws
