#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

if [ ! -z "$EXTRA_APT_PACKAGES" ]; then
    echo "EXTRA_APT_PACKAGES environment variable found.  Installing ${EXTRA_APT_PACKAGES}"
    apt update -y
    apt install -y $EXTRA_APT_PACKAGES
fi

if [ ! -z "$EXTRA_PIP_PACKAGES" ]; then
    echo "EXTRA_PIP_PACKAGES environment variable found.  Installing ${EXTRA_PIP_PACKAGES}"
  pip install $EXTRA_PIP_PACKAGES
fi

if [ ! -z "$EXTRA_CONDA_PACKAGES" ]; then
    echo "EXTRA_CONDA_PACKAGES environment variable found.  Installing ${EXTRA_CONDA_PACKAGES}"
    conda install -y $EXTRA_CONDA_PACKAGES
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
