name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docker-image-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - cmip6-downscaling
          - fire-monitor
          - main
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: ci/environment.yml
          environment-name: conda-lock

      - name: Generate lock files for ${{ matrix.environment }}
        run: |
          cd ${{ matrix.environment }}
          bash 01_setup.sh
          bash 02_make_lock_files.sh

      - name: Build Docker image for ${{ matrix.environment }}
        run: |
          cd ${{ matrix.environment }}
          bash 03_build.sh

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image for ${{ matrix.environment }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ${{ matrix.environment }}
          bash 04_publish.sh
