name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docker-image-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true # default
      matrix:
        environment:
          - cmip6-downscaling
          - fire-monitor
          - main
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: "*"
          environment-name: base
          extra-specs: |
            python=3.10
            conda-lock
      - name: Build environment
        run: |
          cd ${{ matrix.environment }}
          01_setup.sh
          02_make_lock_files.sh
