name: carbonplan
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10

  - adlfs
  - azure-storage-blob
  - awscli
  - boto3
  - bokeh
  - bottleneck
  - cartopy
  - cftime
  - cmip6_preprocessing
  - fastparquet
  - fuzzywuzzy
  - gcsfs
  - gdal
  - geopandas
  - geoviews
  - gh-scoped-creds
  - git
  - git-crypt
  - h5py
  - h5netcdf
  - hvplot
  - hypothesis
  - intake
  - intake-esm
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - matplotlib
  - nc-time-axis
  - netcdf4
  - nodejs
  - numcodecs
  - numpy
  - oauth2client
  - openpyxl
  - pandas
  - pip
  - pre_commit
  - prefect
  - pydap
  - pykdtree
  - pygeos
  - pyjanitor
  - pygraphviz
  - pyproj
  - pyresample
  - pysal
  - pystac
  - pytest
  - python-graphviz
  - python-wget
  - rasterio
  - rechunker
  - regionmask
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - tzdata
  - xarray
  - xesmf
  - xgboost
  - xlrd
  - xpublish
  - yarn
  - zarr

  - pip:
    - prefect-aws
  